### ISSUE TITLE
ReferenceError: connecion is not defined, TypeError

### ISSUE THREAD

**Issue by radonthetyrant** [Mangadex-Archive-Devs/mangadex-req#2]
```
(node:13656) ReferenceError: connecion is not defined
    at getConnection (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:29:25)
    at __req (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:217:12)
    at new Promise (<anonymous>)
    at request (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:221:110)
    at getManga (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:230:25)
    at checkManga (Q:\Documents\mangadex-archive\srv.js:269:5)
    at Promise (Q:\Documents\mangadex-archive\srv.js:110:33)
    at new Promise (<anonymous>)
    at Request.request.get [as _callback] (Q:\Documents\mangadex-archive\srv.js:108:42)
    at Request.self.callback (Q:\Documents\mangadex-archive\node_modules\request\request.js:186:22)
(node:13656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:13656) TypeError: a is not iterable
    at v.reduce (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:138:7)
    at Array.reduce (<anonymous>)
    at Object.mangarev (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:137:27)
    at JSON.parse (<anonymous>)
    at ClientHttp2Stream.manga (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:165:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
```
$ node -v
v8.9.4
```

**Comment by ZaneHannanAU** [comment]
`npm -v` or `npm ls` please.
Current is 2.0.0
use `npm update mangadex-req` if version <2.0.0

**Comment by ZaneHannanAU** [comment]
Oh shit

**Comment by radonthetyrant** [comment]
```
$ npm -v
5.6.0
```
```
$ npm ls | grep mangadex-req
+-- mangadex-req@2.0.0 (git+https://github.com/radonthetyrant/mangadex-req.git#c7f38675913ebb3dc858be5ba89bbdfc1d86c2e0)
```

**Comment by ZaneHannanAU** [comment]
Fixed v2.0.1

**Comment by radonthetyrant** [comment]
```
$ npm ls | grep mangadex-req
+-- mangadex-req@2.0.1 (git+https://github.com/radonthetyrant/mangadex-req.git#14318ae504c091205321dd0c0d997c8a1c4deeda)
```
```
(node:12572) TypeError: a is not iterable
    at v.reduce (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:138:7)
    at Array.reduce (<anonymous>)
    at Object.mangarev (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:137:27)
    at JSON.parse (<anonymous>)
    at ClientHttp2Stream.manga (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:165:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12572) TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.mangarev (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:137:27)
    at JSON.parse (<anonymous>)
    at ClientHttp2Stream.manga (Q:\Documents\mangadex-archive\node_modules\mangadex-req\index.js:165:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ZaneHannanAU** [comment]
Now 2.0.2 I think there's still more
